name: esig-distribution-regression-streams-env
channels:
  - defaults
  - bioconda
  - imperial-college-research-computing
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - ca-certificates=2024.9.24
  - decorator=5.1.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.5
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=1.1.1w
  - packaging=24.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=24.2
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.9.5
  - python-dateutil=2.9.0post0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
    - asttokens==2.4.1
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.3.0
    - cycler==0.12.1
    - cython==3.0.11
    - debugpy==1.8.7
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fbm==0.3.0
    - fonttools==4.54.1
    - iisignature==0.24
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipython==8.18.1
    - joblib==1.4.2
    - jupyter-client==8.6.3
    - kiwisolver==1.4.7
    - llvmlite==0.43.0
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - numba==0.60.0
    - numpy==1.26.4
    - pandas==2.2.3
    - parso==0.8.4
    - pillow==10.4.0
    - platformdirs==4.3.6
    - prompt-toolkit==3.0.48
    - psutil==6.0.0
    - pure-eval==0.2.3
    - pygments==2.18.0
    - pyparsing==3.2.0
    - pytz==2024.2
    - pyzmq==26.2.0
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - signatory==1.2.6.1.9.0
    - stack-data==0.6.3
    - threadpoolctl==3.5.0
    - torch==1.9.0+cpu
    - torchaudio==0.9.0
    - torchvision==0.10.0+cpu
    - tqdm==4.66.5
    - tslearn==0.6.3
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - wcwidth==0.2.13